#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use PPI\PapiInfo\Console\Command\CompileCommand;
use PPI\PapiInfo\Console\Command\VerifyCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CompileCommand());
$application->add(new VerifyCommand());
$application->run();